# Generated by Django 5.2.17 on 2026-09-22 18:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('source_type', models.CharField(choices=[('paste', 'Pasted text'), ('upload', 'Uploaded file')], default='paste', max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('original_text', models.TextField()),
                ('text_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('language', models.CharField(default='en', max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('sentence_count', models.PositiveIntegerField(default=0)),
                ('paragraph_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result_label', models.CharField(blank=True, choices=[('likely_human', 'Likely human'), ('possibly_ai_assisted', 'Possibly AI-assisted'), ('likely_ai_associated', 'Likely AI-associated'), ('uncertain', 'Uncertain'), ('insufficient_evidence', 'Insufficient evidence')], max_length=24)),
                ('ai_probability', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('uncertainty', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('is_demo', models.BooleanField(default=False, help_text='True when produced by the labelled demo detector.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=80)),
                ('feature_value', models.FloatField()),
                ('category', models.CharField(choices=[('document', 'Document'), ('lexical', 'Lexical'), ('syntactic', 'Syntactic'), ('linguistic', 'Linguistic'), ('statistical', 'Statistical'), ('semantic', 'Semantic'), ('stylometric', 'Stylometric'), ('structural', 'Structural')], max_length=12)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='analyzer.analysis')),
            ],
            options={
                'ordering': ['category', 'feature_name'],
            },
        ),
        migrations.CreateModel(
            name='SentenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('start_char', models.PositiveIntegerField()),
                ('end_char', models.PositiveIntegerField()),
                ('ai_probability', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='analyzer.analysis')),
            ],
            options={
                'verbose_name_plural': 'sentence analyses',
                'ordering': ['analysis', 'sentence_index'],
            },
        ),
        migrations.AddIndex(
            model_name='analysis',
            index=models.Index(fields=['user', '-created_at'], name='analyzer_an_user_id_a872c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(('ai_probability__isnull', True), models.Q(('ai_probability__gte', 0.0), ('ai_probability__lte', 1.0)), _connector='OR'), name='analysis_ai_probability_0_1'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='analysis_confidence_0_1'),
        ),
        migrations.AddConstraint(
            model_name='analysis',
            constraint=models.CheckConstraint(condition=models.Q(('uncertainty__isnull', True), models.Q(('uncertainty__gte', 0.0), ('uncertainty__lte', 1.0)), _connector='OR'), name='analysis_uncertainty_0_1'),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('analysis', 'feature_name'), name='unique_feature_per_analysis'),
        ),
        migrations.AddConstraint(
            model_name='sentenceanalysis',
            constraint=models.UniqueConstraint(fields=('analysis', 'sentence_index'), name='unique_sentence_per_analysis'),
        ),
        migrations.AddConstraint(
            model_name='sentenceanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('end_char__gte', models.F('start_char'))), name='sentence_span_ordered'),
        ),
        migrations.AddConstraint(
            model_name='sentenceanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('ai_probability__isnull', True), models.Q(('ai_probability__gte', 0.0), ('ai_probability__lte', 1.0)), _connector='OR'), name='sentence_ai_probability_0_1'),
        ),
        migrations.AddConstraint(
            model_name='sentenceanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='sentence_confidence_0_1'),
        ),
    ]
