# Generated by Django 5.2.17 on 2026-09-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='pipeline_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='analysis',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='processing_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='report',
            field=models.JSONField(blank=True, default=dict, help_text='Structured results: top words, repeated phrases, notes.'),
        ),
    ]
